let e = 10;
let f = function() {
    e++;
    return e;
}
try {

} catch (e) {
    console.log(e);
}
